baseURL = "https://heesungb.github.io/blog/"
languageCode = "en-us"
title = "Heesung's Blog"
theme = "mixedpaper"
enableRobotsTXT = true
paginate = 3 # Set the number of posts to show before overflowing to the next page.
summaryLength = 100 # Configure how long the post summary should be on the homepage.
pygmentsUseClasses = true # enable theme-defined highlight style
hasCJKLanguage = false

[taxonomies]
tag = "tags"

[author]
name = "Hugo Author"

[params]
# Blog description at the top of the homepage. Supports markdown.
description = "Mixedpaper is a minimalist Hugo theme, perfect for writers and bloggers."
showReadMore = false
mainSections = [
	"posts",
]

# paginate of archives, tags and categories
listPaginate = 20
postLicense = ""


[[menu.main]]
identifier = "tags"
name = "Tags"
url = "tags/"
weight = 2

[[menu.main]]
name = "Posts"
identifier = "posts"
url = "posts/"
weight = 1


[params.comment]
type = "none"

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true